INSERT INTO produit (id_produit, lib_produit_fr, lib_produit, prix_produit, stock, description, description_fr, id_mat_fr, id_cat)
VALUES
(21, 'Table basse en chêne', 'Oak coffee table', 199.99, 10, 'This beautiful coffee table is made of high-quality oak wood and features a modern design.', 'Cette belle table basse est fabriquée en chêne de haute qualité et présente un design moderne.',1,3),
(22, 'Table à manger en verre', 'Glass dining table', 499.99, 5, 'This elegant dining table is made of tempered glass and is perfect for family dinners or hosting guests.', 'Cette élégante table à manger est en verre trempé et convient parfaitement aux dîners de famille ou à la réception d\'invités.',1,3),
(23, 'Table de chevet en pin', 'Pine bedside table', 99.99, 15, 'This charming bedside table is made of durable pine wood and features a convenient drawer for storage.', 'Cette charmante table de chevet est en pin durable et comporte un tiroir pratique pour le rangement.',1,3),
(24, 'Table de bureau en acier', 'Steel office table', 349.99, 8, 'This sturdy office table is made of high-quality steel and is perfect for a modern workspace.', 'Cette solide table de bureau est en acier de haute qualité et convient parfaitement à un espace de travail moderne.',1,3),
(25, 'Table pliante en plastique', 'Folding plastic table', 79.99, 20, 'This practical folding table is made of durable plastic and is perfect for outdoor gatherings or events.', 'Cette table pliante pratique est en plastique durable et convient parfaitement aux rassemblements ou événements en extérieur.',1,3),
(26, 'Table d\'appoint en marbre', 'Marble side table', 299.99, 7, 'This luxurious side table features a beautiful marble top and is perfect for adding a touch of elegance to any room.', 'Cette luxueuse table d\'appoint est dotée d\'un magnifique plateau en marbre et convient parfaitement pour ajouter une touche d\'élégance à n\'importe quelle pièce.',1,3),
(27, 'Table de jardin en aluminium', 'Aluminum garden table', 249.99, 6, 'This stylish garden table is made of lightweight aluminum and is perfect for outdoor dining or relaxing.', 'Cette élégante table de jardin est en aluminium léger et convient parfaitement pour les repas ou la détente en extérieur.',1,3),
(28, 'Table pliante en bois', 'Wooden folding table', 149.99, 12, 'This versatile folding table is made of sturdy wood and is perfect for picnics, camping, or any outdoor activity.', 'Cette table pliante polyvalente est en bois robuste et convient parfaitement aux pique-niques, camping ou toute activité en extérieur.',1,3),
(29, 'Table d\'appoint en acier inoxydable', 'Stainless steel side table', 199.99, 9, 'This sleek side table is made of high-quality stainless steel and is perfect for a modern living room.', 'Cette élégante table d\'appoint est en acier inoxydable de haute qualité et convient parfaitement dans peu importe la pièce de votre maison',1,3),
(30, 'Table de nuit en bois', 'Wooden Nightstand', 129.99, 14, 'This sturdy wooden nightstand is perfect for your bedroom.', 'Cette table de nuit en bois robuste est parfaite pour votre chambre.',1,3);